---
sudo: required
language: ruby
cache: bundler
dist: trusty

services:
- docker

gemfile:
- Gemfile
- gemfile.chef-11

before_install:
- gem install bundler
- gem --version

matrix:
  include:
  - rvm: 1.9.3
    gemfile: Gemfile
    bundler_args: "--without integration guard tools"
  - rvm: 1.9.3
    gemfile: gemfile.chef-11
    bundler_args: "--without integration guard tools"
  - rvm: 2.2.4
    gemfile: Gemfile
    bundler_args: "--without integration guard tools"
  - rvm: 2.2.4
    gemfile: gemfile.chef-11
    bundler_args: "--without integration guard tools"
  - rvm: ruby-head
    gemfile: Gemfile
    bundler_args: "--without integration guard tools"
  - rvm: ruby-head
    gemfile: gemfile.chef-11
    bundler_args: "--without integration guard tools"
  - rvm: 2.2.4
    bundler_args: "--without guard tools"
    script: bundle exec rake test:integration OS='centos oracle'
    gemfile: Gemfile
  - rvm: 2.2.4
    bundler_args: "--without guard tools"
    script: bundle exec rake test:integration OS='ubuntu debian'
    gemfile: Gemfile
